#! /bin/sh -e
# /usr/lib/emacsen-common/packages/install/org-mode

# Written by Jim Van Zandt <jrv@debian.org>, borrowing heavily
# from the install scripts for gettext by Santiago Vila
# <sanvila@ctv.es> and octave by Dirk Eddelbuettel <edd@debian.org>.

FLAVOR=$1
PACKAGE=org-mode
STAMPFILE=org-wl.elc
LOG=$(tempfile -pelc_ -s.log -m644)

case ${FLAVOR} in
  emacs) exit 0 ;; # generic emacs package
  emacs21) exit 0 ;; # not supported anymore as of 6.26a-3
  emacs22) exit 0 ;; # not supported anymore as of 8.x
  xemacs*) exit 0 ;; # not supported anymore as of 7.x
esac

echo "install/${PACKAGE}: Handling install for emacsen flavor ${FLAVOR}, logged in ${LOG}"

FLAVORTEST=$(echo $FLAVOR | cut -c-6)
SITEFLAG="--no-site-file"
FILES="/usr/share/emacs/site-lisp/${PACKAGE}/*.el"
DATAFILES="/usr/share/emacs/site-lisp/${PACKAGE}/etc/styles/*.xml"
DATADIR="/usr/share/${FLAVOR}/site-lisp/${PACKAGE}/etc/styles"

mkdir -p ${DATADIR}
cd ${DATADIR}
for i in ${DATAFILES}; do
  ln -fs $i
done

ELCDIR=/usr/share/${FLAVOR}/site-lisp/${PACKAGE}
install -m 755 -d ${ELCDIR}
cd ${ELCDIR}
for i in ${FILES}; do
    ln -fs $i
done
if [ -n "$EXCLUDE_FILES" ] ; then
  rm -f ${ELCDIR}/${EXCLUDE_FILES}
fi

FLAGS="${SITEFLAG} -q -batch -l path.el -f batch-byte-compile"

cat << EOF > path.el
(setq load-path (cons "." load-path))
(setq byte-compile-warnings nil)
EOF

echo ${FLAVOR} ${FLAGS} *.el > ${LOG}
${FLAVOR} ${FLAGS} *.el >> ${LOG} 2>& 1
egrep -s -e "While compiling|\*\*" ${LOG} || /bin/true
echo install/${PACKAGE}: Deleting ${LOG}
rm -f path.el*

exit 0
