#!/bin/sh -e
# /usr/lib/emacsen-common/packages/remove/org-mode

FLAVOR=$1
PACKAGE=org-mode

case ${FLAVOR} in
  emacs) exit 0 ;; # generic emacs package
  emacs21) exit 0 ;; # not supported anymore as of 6.26a-3
esac

echo remove/${PACKAGE}: purging byte-compiled files for ${FLAVOR}
rm -rf /usr/share/${FLAVOR}/site-lisp/${PACKAGE}
